### ISSUE TITLE
Delete_keys failing to compile

### ISSUE THREAD

**Issue by sarchak** [basho/riak_function_contrib#21]
Hi All,
I am trying to compile the the delete_keys.erl and its failing as below.
I dont have much knowledge about Erlang.

%% -------------------------------------------------------------------

-module(reduce_functions).

-export([delete/2]).

% Data is a list of bucket and key pairs, intermixed with the counts of deleted
% objects. Returns a count of deleted objects.
delete(List, _None) ->
  {ok, C} = riak:local_client(),

  Delete = fun(Bucket, Key) ->
    case C:delete(Bucket, Key, 0) of
      ok -> 1;
      _ -> 0
    end
  end,

  F = fun(Elem, Acc) ->
    case Elem of
      {{Bucket, Key}, _KeyData} ->
        Acc + Delete(Bucket, Key);
      {Bucket, Key} ->
        Acc + Delete(Bucket, Key);
      [Bucket, Key] ->
        Acc + Delete(Bucket, Key);
      _ ->
        Acc + Elem
    end
  end,

  [lists:foldl(F, 0, List)]

electic@riak-1:~/modules$ /usr/lib/riak/erts-5.9.1/bin/erlc delete_keys.erl
delete_keys.erl:50: syntax error before:
delete_keys.erl:23: function delete/2 undefined

Am I missing something?
Thanks,
Shrikar

**Comment by bsparrow435** [comment]
Fixed with #22
